spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/trainingdb
    username: root
    password: aniruddha
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate:
        format_sql: true
    